name: install, build & start

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    name: install, build & start
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Project
      run: npm install
    - name: Build Project
      run: CI=false npm run build
    - name: Start Project
      run: npm start & npx wait-on http://localhost:3000
    - name: config1
      run: git config --global user.email "arasto.sahbaei@gmail.com"
    - name: config2
      run: git config --global user.name "Arasto Sahbaei"
    - name: Deploy Project
      run: CI=false npm run deploy