name: npm install && npm start

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    name: npm install && npm start
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Project
      run: npm install
    - name: Start Project
      run: npm start