name: install, build & start

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    name: install, build & start
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Project
      run: npm install

    - name: Build Project
      run: CI=false npm run build
      
    - name: Start Project
      run: npm start & npx wait-on http://localhost:3000
      
    - name: Deploy Project
      uses: ArastoSahbaei/github-pages-deploy-action@v4
      with:
        folder: build
        branch: gh-pages 